In [84]:
import pandas as pd

In [85]:
import numpy as np

In [86]:
pessoas13 = pd.read_excel("dados_entrada\Tabelas_2000\Convertidas\Pessoas13_PE_M.xlsx")

In [90]:
resultado = pd.read_excel("dados_saida\Resultado_2000\excel\ResultadoGeral.xlsx",index=False)

In [91]:
def V13(V022,V035,V036,V037,V038,V039,V040,V041,V042,V043,V044,V045,V046,V047,V048,V002):
    return (((V022+V035+V036+V037+V038+V039+V040+V041+V042+V043+V044+V045+V046+V047+V048)/V002)*100)

In [92]:
def V14(V099,V100,V101,V102,V103,V104,V105,V106,V107,V108,V109,V110,V111,V112,V113,V114,V115,V116,V117,V118,V119,V120,V121,V122,V123,V124,V125,V126,V127,V128,V129,V130,V131,V132,V133,V134,V002):
    return (((V099+V100+V101+V102+V103+V104+V105+V106+V107+V108+V109+V110+V111+V112+V113+V114+V115+V116+V117+V118+V119+V120+V121+V122+V123+V124+V125+V126+V127+V128+V129+V130+V131+V132+V133+V134)/V002)*100)

In [95]:
resultado['V13'] = pessoas13.apply(lambda x: V13(x.V022, x.V035, x.V036, x.V037, x.V038, x.V039, x.V040, x.V041, x.V042, x.V043, x.V044, x.V045, x.V046, x.V047, x.V048, x.V002), axis=1)

In [96]:
resultado['V14'] = pessoas13.apply(lambda x: V14(x.V099, x.V100, x.V101, x.V102, x.V103, x.V104, x.V105, x.V106, x.V107, x.V108, x.V109, x.V110, x.V111, x.V112, x.V113, x.V114, x.V115, x.V116, x.V117, x.V118, x.V119, x.V120, x.V121, x.V122, x.V123, x.V124, x.V125, x.V126, x.V127, x.V128, x.V129, x.V130, x.V131, x.V132, x.V133, x.V134, x.V002), axis=1)

In [99]:
resultado.to_excel("dados_saida\Resultado_2000\excel\ResultadoGeral.xlsx",index=False)

In [100]:
resultado.to_csv("dados_saida\Resultado_2000\csv\ResultadoGeral.csv",index=False)

In [101]:
resultado

,Cod_setor,V001,V002,V003,V004,V005,V006,V007,V008,V009,...,V113,V114,V115,V116,V117,V118,V119,V11,V13,V14
0,260005405000001,201.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,105.472637,32.338308
1,260005405000002,340.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,105.294118,25.000000
2,260005405000003,424.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.000000,99.764151,22.405660
3,260005405000004,450.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.222222,89.777778,25.777778
4,260005405000005,407.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.245700,100.245700,24.078624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,261650605000013,153.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.960784,188.888889,30.718954
8554,261650605000014,98.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,222.448980,12.244898
8555,261650605000015,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,226.190476,14.285714
8556,261650605000016,111.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,185.585586,18.018018
8557,261650605000017,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,168.316832,22.772277