In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
responsavel02 = pd.read_excel("dados_entrada\Tabelas_2000\Convertidas\Responsavel02_PE_M.xlsx")

In [4]:
resultado = pd.read_excel("dados_saida\Resultado_2000\excel\ResultadoGeral.xlsx",index=False)

In [5]:
def V09(V002, V003, V004, V005, V006, V007, V008, V009, V010, V011, V001):
    return (((V002+V003+V004+V005+V006+V007+V008+V009+V010+V011)/V001)*100)

In [6]:
def V10(V057, V058, V059, V060, V061, V062, V063, V064, V065, V066, V067, V068, V069, V070, V071, V072, V073, V074, V075, V076, V077, V078, V079, V080, V081, V082, V083, V084, V085, V086, V087, V088, V089, V090, V091, V092, V001):
    return (((V057+V058+V059+V060+V061+V062+V063+V064+V065+V066+V067+V068+V069+V070+V071+V072+V073+V074+V075+V076+V077+V078+V079+V080+V081+V082+V083+V084+V085+V086+V087+V088+V089+V090+V091+V092)/V001)*100)

In [7]:
def V15(V001, V093):
    return (((V001/V093)/V001)*100)

In [8]:
resultado['V09'] = responsavel02.apply(lambda x: V09(x.V002,x.V003, x.V004, x.V005, x.V006, x.V007, x.V008,x.V009, x.V010, x.V011, x.V001), axis=1)

In [9]:
resultado['V10'] = responsavel02.apply(lambda x: V10(x.V057, x.V058, x.V059, x.V060, x.V061, x.V062, x.V063, x.V064, x.V065, x.V066, x.V067, x.V068, x.V069, x.V070, x.V071, x.V072, x.V073, x.V074, x.V075, x.V076, x.V077, x.V078, x.V079, x.V080, x.V081, x.V082, x.V083, x.V084, x.V085, x.V086, x.V087, x.V088, x.V089, x.V090, x.V091, x.V092, x.V001), axis=1)

In [10]:
resultado['V15'] = responsavel02.apply(lambda x: V15(x.V001, x.V093), axis=1)

C:\Users\frank\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in double_scalars

In [11]:
resultado.to_excel("dados_saida\Resultado_2000\excel\ResultadoGeral.xlsx",index=False)

In [12]:
resultado.to_csv("dados_saida\Resultado_2000\csv\ResultadoGeral.csv",index=False)

In [13]:
resultado

,Cod_setor,V001,V002,V003,V004,V005,V006,V007,V008,V009,...,V115,V116,V117,V118,V119,V11,V12,V09,V10,V15
0,260005405000001,201.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,11.442786,0.000000,24.875622,0.662252
1,260005405000002,340.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,7.941176,0.294118,16.470588,0.350877
2,260005405000003,424.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.000000,6.603774,0.471698,14.386792,0.295858
3,260005405000004,450.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.222222,9.333333,0.444444,18.888889,0.265252
4,260005405000005,407.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.245700,7.371007,1.228501,16.953317,0.337838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,261650605000013,153.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,1.960784,6.535948,3.267974,22.222222,1.428571
8554,261650605000014,98.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,1.020408,1.020408,10.204082,4.000000
8555,261650605000015,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,11.904762,5.263158
8556,261650605000016,111.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,2.702703,0.000000,12.612613,2.857143
8557,261650605000017,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,4.000000,0.000000,14.000000,3.846154